-- ============================================
-- Origami Database Tables for Supabase
-- All tables prefixed with origami_
-- Completely separate from existing app tables
-- No foreign keys - flat import
-- ============================================

-- Carriers
CREATE TABLE IF NOT EXISTS origami_carriers (
  carrier_id integer PRIMARY KEY,
  display_code varchar(8),
  client_id integer,
  description varchar(250),
  legal_name varchar(100),
  fein varchar(10),
  type_of_insurer char(1),
  is_inactive boolean,
  parent_carrier_id integer,
  am_best_rating char(1),
  standard_and_poor_rating char(1),
  financial_category char(1),
  naic_number varchar(8),
  inactive_date date,
  mailing_name varchar(70),
  address1 varchar(50),
  address2 varchar(50),
  city varchar(50),
  state_id integer,
  postal_code varchar(20),
  site_id varchar(9),
  phone_number varchar(15),
  fax varchar(15),
  email varchar(50),
  ncci_code varchar(5),
  county varchar(25),
  state_license_number varchar(50),
  am_best_number integer,
  am_best_parent_number integer,
  am_best_rating_outlook char(1),
  am_best_rating_action char(1),
  am_best_effective_date timestamp,
  sequence integer,
  billing_name varchar(250),
  billing_street1 varchar(250),
  billing_street2 varchar(250),
  billing_city varchar(50),
  billing_state_id integer,
  billing_postal_code varchar(50),
  entry_user_id integer,
  entry_date timestamp,
  modified_user_id integer,
  modified_date timestamp
);

-- Clients
CREATE TABLE IF NOT EXISTS origami_clients (
  client_id integer PRIMARY KEY,
  name varchar(100),
  is_active boolean,
  global_id uuid,
  url_prefix varchar(50),
  street1 varchar(250),
  street2 varchar(50),
  city varchar(50),
  state varchar(50),
  postal_code varchar(50),
  primary_contact_user_id integer,
  primary_contact_name varchar(100),
  primary_contact_email varchar(256),
  primary_contact_phone varchar(50),
  reference_number varchar(25),
  manage_global_records_flag boolean,
  client_type_id integer,
  entry_date timestamp,
  entry_user_id integer,
  modified_date timestamp,
  modified_user_id integer,
  carrier_id integer,
  broker_id integer,
  billing_account_id integer,
  logo_image_file_name varchar(200),
  disable_mobile_claimant_app boolean,
  audit_location_values boolean,
  prefunding_amount numeric,
  parent_carrier_id integer
);

-- Claims (core fields only - no CustomText/CustomCode/CustomBool/CustomDate/CustomNumber/CustomMoney/CustomUser/CustomNarrative/CustomMultiSelectCode/CustomContact)
CREATE TABLE IF NOT EXISTS origami_claims (
  claim_id integer PRIMARY KEY,
  client_id integer,
  coverage_id integer,
  claim_number varchar(30),
  claim_sequence integer,
  occurrence_number varchar(30),
  prior_claim_number varchar(30),
  claim_office_id integer,
  claim_adjuster_name varchar(50),
  claim_adjuster_phone varchar(50),
  site varchar(50),
  incident_id integer,
  loss_date date,
  loss_day_of_week smallint,
  loss_time smallint,
  report_date date,
  employer_report_date date,
  first_claimant_contact_date date,
  last_claimant_contact_date date,
  last_close_date date,
  first_close_date date,
  last_reopen_date date,
  location_id integer,
  accident_state_id integer,
  jurisdiction_state_id integer,
  claimant varchar(250),
  social_security varchar(9),
  loss_description text,
  event_description text,
  major_injury char(1),
  source_id integer,
  carrier_id integer,
  cause_id integer,
  body_part_id integer,
  nature_id integer,
  excess boolean,
  subrogation boolean,
  rehabilitation boolean,
  surgery boolean,
  lawsuit_filed boolean,
  suit_date date,
  suit_result char(1),
  suit_type char(1),
  lawsuit_likely boolean,
  status char(1),
  detail_status char(1),
  reference_number varchar(21),
  policy_id integer,
  osha_recordable boolean,
  disability_date date,
  last_worked_date date,
  rtw_full_date date,
  rtw_restricted_date date,
  lost_days smallint,
  restricted_days smallint,
  osha_code char(1),
  claimant_address1 varchar(150),
  claimant_address2 varchar(150),
  claimant_city varchar(50),
  claimant_state_id integer,
  claimant_postal_code varchar(20),
  claimant_country_id integer,
  claimant_home_phone varchar(20),
  claimant_work_phone varchar(20),
  claimant_email varchar(50),
  claimant_age smallint,
  birth_date date,
  death_date date,
  number_of_dependents smallint,
  marital_status char(1),
  gender char(1),
  hire_date date,
  length_of_service integer,
  state_assigned_claim_number varchar(25),
  job_classification_id integer,
  occupation varchar(50),
  department_name varchar(50),
  department_id integer,
  supervisor varchar(50),
  law_firm varchar(50),
  lead_attorney varchar(50),
  court varchar(50),
  expected_settlement_amount numeric,
  actual_settlement_amount numeric,
  last_settlement_offer_given numeric,
  last_settlement_offer_received numeric,
  employment_status char(1),
  average_weekly_wage numeric,
  vin varchar(20),
  vehicle_make varchar(25),
  vehicle_model varchar(50),
  vehicle_year smallint,
  driver_name varchar(50),
  drivers_license_number varchar(20),
  drivers_license_state_id integer,
  driver_age smallint,
  driver_gender char(1),
  driver_chargeable varchar(10),
  loss_payee_name varchar(50),
  product_name varchar(50),
  product_id integer,
  entry_date timestamp,
  entry_user_id integer,
  modified_date timestamp,
  modified_user_id integer,
  first_transaction_date date,
  last_transaction_date date,
  paid1 numeric,
  paid2 numeric,
  paid3 numeric,
  paid4 numeric,
  paid5 numeric,
  paid6 numeric,
  paid7 numeric,
  reserve1 numeric,
  reserve2 numeric,
  reserve3 numeric,
  reserve4 numeric,
  reserve5 numeric,
  reserve6 numeric,
  reserve7 numeric,
  recovery1 numeric,
  recovery2 numeric,
  recovery3 numeric,
  recovery4 numeric,
  recovery5 numeric,
  recovery6 numeric,
  recovery7 numeric,
  record_only1 numeric,
  record_only2 numeric,
  record_only3 numeric,
  record_only4 numeric,
  record_only5 numeric,
  record_only6 numeric,
  record_only7 numeric,
  tpa_claim_number varchar(30),
  carrier_policy_number varchar(50),
  carrier_policy_effective_date timestamp,
  event_location varchar(250),
  accident_type_id integer,
  preventable boolean,
  dot_recordable boolean,
  accident_longitude numeric,
  accident_latitude numeric,
  detail_cause_id integer,
  detail_body_part_id integer,
  detail_nature_id integer,
  detail_accident_type_id integer,
  lead_claim boolean,
  settlement_date date,
  suit_response_date date,
  wc_benefit_type char(1),
  initial_treatment_code char(1),
  employee_number varchar(25),
  adjuster_user_id integer,
  hicn varchar(12),
  excess_policy_id integer,
  discovery_date date,
  resolution_date date,
  answer_date date,
  assignment_date date,
  trial_date date,
  mediation_date date,
  escrow_amount numeric,
  alleged_damages numeric,
  estimated_verdict_value numeric,
  case_overview text,
  summary_of_facts text,
  verdict_comments text,
  docket_number varchar(25),
  case_number varchar(25),
  defense_counsel_attorney varchar(50),
  defense_counsel_firm varchar(100),
  plaintiff_counsel_attorney varchar(50),
  plaintiff_counsel_firm varchar(100),
  accident_street1 varchar(150),
  accident_street2 varchar(150),
  accident_city varchar(50),
  accident_postal_code varchar(20),
  secondary_location_id integer,
  employee_id integer,
  vehicle_id integer,
  policy_coverage_id integer,
  is_cancelled boolean,
  is_private boolean,
  acquired_claim boolean,
  single_claim_occurrence boolean,
  catastrophe_id integer,
  program_id integer,
  member_id integer,
  currency_id integer,
  loss_event_id integer
);

-- Codes (lookup table)
CREATE TABLE IF NOT EXISTS origami_codes (
  code_id integer PRIMARY KEY,
  client_id integer,
  display_code varchar(16),
  description varchar(250),
  major_coverage_id integer,
  code_type_id integer,
  is_inactive boolean,
  sequence integer,
  inactive_date date,
  edi varchar(10),
  major_coverage_ids varchar(250)
);

-- Hierarchies
CREATE TABLE IF NOT EXISTS origami_hierarchies (
  hierarchy_id integer PRIMARY KEY,
  client_id integer,
  name varchar(50),
  level1_label varchar(50),
  level2_label varchar(50),
  level3_label varchar(50),
  level4_label varchar(50),
  level5_label varchar(50),
  level6_label varchar(50),
  level7_label varchar(50),
  level8_label varchar(50),
  level9_label varchar(50),
  level10_label varchar(50)
);

-- Incidents
CREATE TABLE IF NOT EXISTS origami_incidents (
  incident_id integer PRIMARY KEY,
  client_id integer,
  incident_type_id integer,
  incident_number varchar(30),
  status char(1),
  claimant varchar(250),
  birth_date date,
  claimant_age smallint,
  gender char(1),
  marital_status char(1),
  loss_date date,
  loss_time smallint,
  report_date date,
  employer_report_date date,
  location_id integer,
  accident_street1 varchar(150),
  accident_city varchar(50),
  accident_county varchar(50),
  accident_state_id integer,
  accident_postal_code varchar(20),
  time_began_work smallint,
  death_date date,
  cause_id integer,
  social_security varchar(9),
  event_description text,
  loss_description text,
  activity_during_accident text,
  object_causing_injury text,
  major_injury char(1),
  nature_id integer,
  body_part_id integer,
  osha_recordable boolean,
  osha_case_number varchar(20),
  claimant_address1 varchar(150),
  claimant_address2 varchar(150),
  claimant_city varchar(50),
  claimant_state_id integer,
  claimant_postal_code varchar(20),
  claimant_country_id integer,
  claimant_home_phone varchar(20),
  claimant_work_phone varchar(20),
  hire_date date,
  occupation varchar(50),
  department_name varchar(50),
  supervisor varchar(50),
  employment_status char(1),
  average_weekly_wage numeric,
  date_of_first_treatment date,
  last_worked_date date,
  hospital_name varchar(50),
  hospital_street1 varchar(150),
  hospital_city varchar(50),
  hospital_state_id integer,
  hospital_postal_code varchar(20),
  physician_name varchar(50),
  physician_address varchar(150),
  physician_phone varchar(20),
  driver_name varchar(50),
  vehicle_make varchar(25),
  vehicle_model varchar(50),
  vehicle_year smallint,
  drivers_license_number varchar(20),
  drivers_license_state_id integer,
  vin varchar(20),
  entry_date timestamp,
  entry_user_id integer,
  modified_date timestamp,
  modified_user_id integer
);

-- Locations
CREATE TABLE IF NOT EXISTS origami_locations (
  location_id integer PRIMARY KEY,
  client_id integer,
  display_code varchar(16),
  description varchar(250),
  status_id integer,
  street1 varchar(250),
  street2 varchar(50),
  city varchar(50),
  state_id integer,
  postal_code varchar(20),
  county varchar(25),
  country varchar(50),
  country_id integer,
  fein varchar(10),
  is_inactive boolean,
  parent_location_id integer,
  site_id varchar(9),
  sequence integer,
  longitude numeric,
  latitude numeric,
  phone_number varchar(15),
  fax varchar(15),
  email varchar(50),
  primary_contact_user_id integer,
  entry_date timestamp,
  entry_user_id integer,
  modified_date timestamp,
  modified_user_id integer
);

-- Location Values (SOV data per policy per location)
CREATE TABLE IF NOT EXISTS origami_location_values (
  location_value_id integer PRIMARY KEY,
  client_id integer,
  policy_id integer,
  location_id integer,
  number integer,
  description varchar(250),
  street1 varchar(250),
  street2 varchar(50),
  city varchar(50),
  state_id integer,
  postal_code varchar(20),
  county varchar(25),
  country varchar(50),
  country_id integer,
  building_value numeric,
  contents_value numeric,
  bi_value numeric,
  other_value numeric,
  total_insured_value numeric,
  premium numeric,
  occupancy varchar(250),
  deductible numeric,
  deductible_type char(1),
  year_built integer,
  number_of_stories integer,
  number_of_units integer,
  square_footage integer,
  construction_type_id integer,
  roof_type_id integer,
  sprinkler_type_id integer,
  flood_zone_id integer,
  protection_class_id integer,
  longitude numeric,
  latitude numeric,
  is_audit_approved boolean,
  audit_approved_by_user_id integer,
  audit_approved_date timestamp,
  roof_age integer,
  plumbing_age integer,
  electrical_age integer,
  hvac_age integer,
  roof_condition_id integer,
  fein varchar(10),
  location_value_sequence integer,
  entry_date timestamp,
  entry_user_id integer,
  modified_date timestamp,
  modified_user_id integer
);

-- Policies
CREATE TABLE IF NOT EXISTS origami_policies (
  policy_id integer PRIMARY KEY,
  client_id integer,
  display_code varchar(16),
  description varchar(250),
  policy_number varchar(50),
  effective_date date,
  expiration_date date,
  major_coverage_id integer,
  self_insured boolean,
  status char(1),
  policy_type_id integer,
  premium numeric,
  notes text,
  program_id integer,
  currency_id integer,
  claims_made_date date,
  sequence integer,
  entry_date timestamp,
  entry_user_id integer,
  modified_date timestamp,
  modified_user_id integer
);

-- Policy Carriers
CREATE TABLE IF NOT EXISTS origami_policy_carriers (
  policy_carrier_id integer PRIMARY KEY,
  client_id integer,
  policy_id integer,
  carrier_id integer,
  policy_number varchar(50),
  participation numeric,
  attachment_point numeric,
  "limit" numeric,
  premium numeric,
  layer_number integer,
  commission numeric,
  commission_amount numeric,
  deductible numeric,
  sir numeric,
  aggregate_limit numeric,
  per_occurrence_limit numeric,
  notes text,
  entry_date timestamp,
  entry_user_id integer,
  modified_date timestamp,
  modified_user_id integer
);

-- Policy Coverages
CREATE TABLE IF NOT EXISTS origami_policy_coverages (
  policy_coverage_id integer PRIMARY KEY,
  client_id integer,
  policy_id integer,
  coverage_id integer,
  description varchar(250),
  "limit" numeric,
  deductible numeric,
  premium numeric,
  sir numeric,
  attachment_point numeric,
  aggregate_limit numeric,
  per_occurrence_limit numeric,
  each_accident_limit numeric,
  disease_each_employee_limit numeric,
  disease_policy_limit numeric,
  notes text,
  entry_date timestamp,
  entry_user_id integer,
  modified_date timestamp,
  modified_user_id integer
);

-- Policy Named Insureds
CREATE TABLE IF NOT EXISTS origami_policy_named_insureds (
  policy_named_insured_id integer PRIMARY KEY,
  client_id integer,
  policy_id integer,
  description varchar(250),
  entry_date timestamp,
  entry_user_id integer,
  modified_date timestamp,
  modified_user_id integer
);

-- Territories
CREATE TABLE IF NOT EXISTS origami_territories (
  territory_id integer PRIMARY KEY,
  client_id integer,
  hierarchy_id integer,
  parent_territory_id integer,
  level smallint,
  display_code varchar(50),
  description varchar(250),
  is_inactive boolean,
  sequence integer,
  entry_date timestamp,
  entry_user_id integer,
  modified_date timestamp,
  modified_user_id integer
);

-- Notes (diary entries tied to claims, incidents, etc.)
CREATE TABLE IF NOT EXISTS origami_notes (
  note_id integer PRIMARY KEY,
  parent_domain_id integer,
  parent_id integer NOT NULL,
  subject varchar(256),
  body text,
  author_name varchar(150),
  entry_date timestamptz,
  modified_date timestamptz,
  note_type_id integer,
  client_id integer,
  entry_user_id integer
);

CREATE INDEX IF NOT EXISTS idx_origami_notes_parent ON origami_notes(parent_domain_id, parent_id);

-- Users
CREATE TABLE IF NOT EXISTS origami_users (
  user_id integer PRIMARY KEY,
  first_name varchar(50),
  last_name varchar(50),
  email varchar(256),
  title varchar(50),
  company_name varchar(250),
  is_inactive boolean
);

-- Enable RLS on all origami tables (no policies = no access via anon key)
ALTER TABLE origami_carriers ENABLE ROW LEVEL SECURITY;
ALTER TABLE origami_clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE origami_claims ENABLE ROW LEVEL SECURITY;
ALTER TABLE origami_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE origami_hierarchies ENABLE ROW LEVEL SECURITY;
ALTER TABLE origami_incidents ENABLE ROW LEVEL SECURITY;
ALTER TABLE origami_locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE origami_location_values ENABLE ROW LEVEL SECURITY;
ALTER TABLE origami_policies ENABLE ROW LEVEL SECURITY;
ALTER TABLE origami_policy_carriers ENABLE ROW LEVEL SECURITY;
ALTER TABLE origami_policy_coverages ENABLE ROW LEVEL SECURITY;
ALTER TABLE origami_policy_named_insureds ENABLE ROW LEVEL SECURITY;
ALTER TABLE origami_territories ENABLE ROW LEVEL SECURITY;
ALTER TABLE origami_notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE origami_users ENABLE ROW LEVEL SECURITY;
